_BASE_: "./Base_ubk_cfg.yaml"
MODEL:
  NAME: "transformer"
SOLVER:
  LR_INIT: 0.01
  MILESTONE: [100, 150]
TRAIN:
  TRAINER: "TransformerTrainer"
  MAX_EPOCH: 200
  LOG_INTERVAL: 50
  SAVE_LAST: True
  OUTPUT_DIR: "results/transformer/"
